// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package vcomponent

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"alvintanoto.id/blog-htmx-templ/internal/dto"
)

func SideNavigation(user *dto.UserDTO) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-base w-full\"><a href=\"/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Home </div></a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if user != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/search/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Search </div></a> <a href=\"/notification/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Notification </div></a> <a href=\"/bookmark/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Bookmark </div></a> <a href=\"/message/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Message </div></a> <a href=\"/draft/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Draft </div></a> <a href=\"/settings/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Settings </div></a> <a href=\"/profile/\"><div class=\"p-2 border-b border-grey-darker cursor-pointer hover:bg-post-hover\">Profile </div></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
